Revert "ID3C barcode slices"
This reverts commit d5cc7335b902c65c85d5e9d1a25949726eb31387.

The "real" work in the related ID3C commit was database changes
for the barcodes slice work. The backoffice change was to run `pipenv
sync`. This updated quite a few packages. We are seeing two issues:

related to fsspec:
File "/opt/backoffice/id3c-production/.venv/lib/python3.6/site-packages/xlrd/__init__.py"
, line 170, in open_workbook raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

related to fhir.resources:
File "/opt/backoffice/id3c-production/.venv/src/id3c/lib/id3c/cli/command/etl/fhir.py", line 113, in etl_fhir
    bundle      = Bundle(record.document)
TypeError: __init__() takes 1 positional argument but 2 were given

The related database changes in ID3C have not been reverted.