uw-ehs-report: Turn off checking of expected vs. updated counts when uploading
While the previous commit made the request to REDCap's API successful,
another error cropped up:

    AssertionError: Expected vs. actual records updated do not match: 8740 != 8739

This comes from redcap.Project.update_records(), which asserts that the
returned count of updated records matches the number of records that it
sent.

With production data, the transfer to the UW EH&S project doesn't pass
this assertion.  It's off by one and it's not clear why even after some
investigation.  I grabbed the actual request data sent and inspected it
briefly for things like a duplicate barcode or empty record that might
make the actual count correct (i.e. would decrease the expected count by
1), but came up empty handed.

I don't know what's going on here yet, and at this point, want to get
the transfer of positives to EH&S going again sooner than later.  Our
previous code (as of this morning), only checked that the count wasn't
zero, and even then, it only warned.  Turn off this check for now,
allowing at the very least the vast majority of the records to transfer.
It leaves us no worse off than before.