id3c-production: Downgrade and pin s3fs to previous version (0.4.2)
The upgrade to s3fs 0.5.0 switched to aiobotocore instead of standard
botocore, which is buggy and threw a TypeError during our manifest
processing:

    File "…/botocore/utils.py", line 1272, in get_bucket_region
        headers = response['ResponseMetadata']['HTTPHeaders']
    TypeError: 'coroutine' object is not subscriptable

Diff best viewed by lumping with the previous commit, to see the sum of
changes without the flip-flop.